### ISSUE TITLE
Make the project 'await' aware

### ISSUE THREAD

**Issue by lpatiny** [image-js/ocr-tools#2]
Please could you help me to allow to use the 'await' so that I can easily test all the images

https://github.com/image-js/ocr-tools/blob/2d8aa3cdec75f5e7953a362b0ec9743a39619f29/run/testPassportRotation.js#L32

**Comment by targos** [comment]
If you don't intend to use async/await in the code of the library, you can just run the script with `node --harmony-async-await test.js`

**Comment by lpatiny** [comment]
OK thanks.

As you pointed out it is mandatory to wrap the code in an async function:
```
(async function() {
   // code here
})()
```
